// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration.proto

#ifndef PROTOBUF_configuration_2eproto__INCLUDED
#define PROTOBUF_configuration_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Beta {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_configuration_2eproto();
void protobuf_AssignDesc_configuration_2eproto();
void protobuf_ShutdownFile_configuration_2eproto();

class ConfigurationProto;

// ===================================================================

class ConfigurationProto : public ::google::protobuf::Message {
 public:
  ConfigurationProto();
  virtual ~ConfigurationProto();

  ConfigurationProto(const ConfigurationProto& from);

  inline ConfigurationProto& operator=(const ConfigurationProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigurationProto& default_instance();

  void Swap(ConfigurationProto* other);

  // implements Message ----------------------------------------------

  ConfigurationProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfigurationProto& from);
  void MergeFrom(const ConfigurationProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 max_depth = 1 [default = 5];
  inline bool has_max_depth() const;
  inline void clear_max_depth();
  static const int kMaxDepthFieldNumber = 1;
  inline ::google::protobuf::int32 max_depth() const;
  inline void set_max_depth(::google::protobuf::int32 value);

  // required int32 num_trees = 2 [default = 3];
  inline bool has_num_trees() const;
  inline void clear_num_trees();
  static const int kNumTreesFieldNumber = 2;
  inline ::google::protobuf::int32 num_trees() const;
  inline void set_num_trees(::google::protobuf::int32 value);

  // required int32 mode = 3 [default = 2];
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 3;
  inline ::google::protobuf::int32 mode() const;
  inline void set_mode(::google::protobuf::int32 value);

  // required float min_entropy = 4 [default = 0.01];
  inline bool has_min_entropy() const;
  inline void clear_min_entropy();
  static const int kMinEntropyFieldNumber = 4;
  inline float min_entropy() const;
  inline void set_min_entropy(float value);

  // required int32 height = 5 [default = 100];
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 5;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // required int32 width = 6 [default = 100];
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 6;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // required int32 context_patch = 7 [default = 50];
  inline bool has_context_patch() const;
  inline void clear_context_patch();
  static const int kContextPatchFieldNumber = 7;
  inline ::google::protobuf::int32 context_patch() const;
  inline void set_context_patch(::google::protobuf::int32 value);

  // required int32 dim_features = 8 [default = 100];
  inline bool has_dim_features() const;
  inline void clear_dim_features();
  static const int kDimFeaturesFieldNumber = 8;
  inline ::google::protobuf::int32 dim_features() const;
  inline void set_dim_features(::google::protobuf::int32 value);

  // required int32 num_keypoints = 9 [default = 10];
  inline bool has_num_keypoints() const;
  inline void clear_num_keypoints();
  static const int kNumKeypointsFieldNumber = 9;
  inline ::google::protobuf::int32 num_keypoints() const;
  inline void set_num_keypoints(::google::protobuf::int32 value);

  // required int32 num_classes = 10 [default = 2];
  inline bool has_num_classes() const;
  inline void clear_num_classes();
  static const int kNumClassesFieldNumber = 10;
  inline ::google::protobuf::int32 num_classes() const;
  inline void set_num_classes(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Beta.ConfigurationProto)
 private:
  inline void set_has_max_depth();
  inline void clear_has_max_depth();
  inline void set_has_num_trees();
  inline void clear_has_num_trees();
  inline void set_has_mode();
  inline void clear_has_mode();
  inline void set_has_min_entropy();
  inline void clear_has_min_entropy();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_context_patch();
  inline void clear_has_context_patch();
  inline void set_has_dim_features();
  inline void clear_has_dim_features();
  inline void set_has_num_keypoints();
  inline void clear_has_num_keypoints();
  inline void set_has_num_classes();
  inline void clear_has_num_classes();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 max_depth_;
  ::google::protobuf::int32 num_trees_;
  ::google::protobuf::int32 mode_;
  float min_entropy_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 context_patch_;
  ::google::protobuf::int32 dim_features_;
  ::google::protobuf::int32 num_keypoints_;
  ::google::protobuf::int32 num_classes_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();

  void InitAsDefaultInstance();
  static ConfigurationProto* default_instance_;
};
// ===================================================================


// ===================================================================

// ConfigurationProto

// required int32 max_depth = 1 [default = 5];
inline bool ConfigurationProto::has_max_depth() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConfigurationProto::set_has_max_depth() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConfigurationProto::clear_has_max_depth() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConfigurationProto::clear_max_depth() {
  max_depth_ = 5;
  clear_has_max_depth();
}
inline ::google::protobuf::int32 ConfigurationProto::max_depth() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.max_depth)
  return max_depth_;
}
inline void ConfigurationProto::set_max_depth(::google::protobuf::int32 value) {
  set_has_max_depth();
  max_depth_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.max_depth)
}

// required int32 num_trees = 2 [default = 3];
inline bool ConfigurationProto::has_num_trees() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConfigurationProto::set_has_num_trees() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConfigurationProto::clear_has_num_trees() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConfigurationProto::clear_num_trees() {
  num_trees_ = 3;
  clear_has_num_trees();
}
inline ::google::protobuf::int32 ConfigurationProto::num_trees() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.num_trees)
  return num_trees_;
}
inline void ConfigurationProto::set_num_trees(::google::protobuf::int32 value) {
  set_has_num_trees();
  num_trees_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.num_trees)
}

// required int32 mode = 3 [default = 2];
inline bool ConfigurationProto::has_mode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConfigurationProto::set_has_mode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConfigurationProto::clear_has_mode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConfigurationProto::clear_mode() {
  mode_ = 2;
  clear_has_mode();
}
inline ::google::protobuf::int32 ConfigurationProto::mode() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.mode)
  return mode_;
}
inline void ConfigurationProto::set_mode(::google::protobuf::int32 value) {
  set_has_mode();
  mode_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.mode)
}

// required float min_entropy = 4 [default = 0.01];
inline bool ConfigurationProto::has_min_entropy() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ConfigurationProto::set_has_min_entropy() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ConfigurationProto::clear_has_min_entropy() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ConfigurationProto::clear_min_entropy() {
  min_entropy_ = 0.01f;
  clear_has_min_entropy();
}
inline float ConfigurationProto::min_entropy() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.min_entropy)
  return min_entropy_;
}
inline void ConfigurationProto::set_min_entropy(float value) {
  set_has_min_entropy();
  min_entropy_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.min_entropy)
}

// required int32 height = 5 [default = 100];
inline bool ConfigurationProto::has_height() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ConfigurationProto::set_has_height() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ConfigurationProto::clear_has_height() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ConfigurationProto::clear_height() {
  height_ = 100;
  clear_has_height();
}
inline ::google::protobuf::int32 ConfigurationProto::height() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.height)
  return height_;
}
inline void ConfigurationProto::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.height)
}

// required int32 width = 6 [default = 100];
inline bool ConfigurationProto::has_width() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ConfigurationProto::set_has_width() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ConfigurationProto::clear_has_width() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ConfigurationProto::clear_width() {
  width_ = 100;
  clear_has_width();
}
inline ::google::protobuf::int32 ConfigurationProto::width() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.width)
  return width_;
}
inline void ConfigurationProto::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.width)
}

// required int32 context_patch = 7 [default = 50];
inline bool ConfigurationProto::has_context_patch() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ConfigurationProto::set_has_context_patch() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ConfigurationProto::clear_has_context_patch() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ConfigurationProto::clear_context_patch() {
  context_patch_ = 50;
  clear_has_context_patch();
}
inline ::google::protobuf::int32 ConfigurationProto::context_patch() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.context_patch)
  return context_patch_;
}
inline void ConfigurationProto::set_context_patch(::google::protobuf::int32 value) {
  set_has_context_patch();
  context_patch_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.context_patch)
}

// required int32 dim_features = 8 [default = 100];
inline bool ConfigurationProto::has_dim_features() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ConfigurationProto::set_has_dim_features() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ConfigurationProto::clear_has_dim_features() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ConfigurationProto::clear_dim_features() {
  dim_features_ = 100;
  clear_has_dim_features();
}
inline ::google::protobuf::int32 ConfigurationProto::dim_features() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.dim_features)
  return dim_features_;
}
inline void ConfigurationProto::set_dim_features(::google::protobuf::int32 value) {
  set_has_dim_features();
  dim_features_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.dim_features)
}

// required int32 num_keypoints = 9 [default = 10];
inline bool ConfigurationProto::has_num_keypoints() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ConfigurationProto::set_has_num_keypoints() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ConfigurationProto::clear_has_num_keypoints() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ConfigurationProto::clear_num_keypoints() {
  num_keypoints_ = 10;
  clear_has_num_keypoints();
}
inline ::google::protobuf::int32 ConfigurationProto::num_keypoints() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.num_keypoints)
  return num_keypoints_;
}
inline void ConfigurationProto::set_num_keypoints(::google::protobuf::int32 value) {
  set_has_num_keypoints();
  num_keypoints_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.num_keypoints)
}

// required int32 num_classes = 10 [default = 2];
inline bool ConfigurationProto::has_num_classes() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ConfigurationProto::set_has_num_classes() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ConfigurationProto::clear_has_num_classes() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ConfigurationProto::clear_num_classes() {
  num_classes_ = 2;
  clear_has_num_classes();
}
inline ::google::protobuf::int32 ConfigurationProto::num_classes() const {
  // @@protoc_insertion_point(field_get:Beta.ConfigurationProto.num_classes)
  return num_classes_;
}
inline void ConfigurationProto::set_num_classes(::google::protobuf::int32 value) {
  set_has_num_classes();
  num_classes_ = value;
  // @@protoc_insertion_point(field_set:Beta.ConfigurationProto.num_classes)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Beta

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_configuration_2eproto__INCLUDED
